# Generated by Django 3.0.5 on 2020-04-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_auto_20200405_0926"),
    ]

    operations = [
        migrations.CreateModel(
            name="WritingPrompt",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                choices=[
                    ("Personnel Santé", "Personnel Santé"),
                    ("Secteur Alimentaire", "Secteur Alimentaire"),
                    ("Education", "Education"),
                    ("Télétravail", "Télétravail"),
                    ("Sécurité", "Sécurité"),
                    ("Transport", "Transport"),
                    ("Etudiant", "Etudiant"),
                    ("Sport", "Sport"),
                    ("Voyage", "Voyage"),
                    ("Art & Culture", "Art & Culture"),
                    ("Cuisine", "Cuisine"),
                    ("Nature & Environnement", "Nature & Environnement"),
                    ("Famille", "Famille"),
                    ("Amitié", "Amitié"),
                    ("Amour", "Amour"),
                    ("Confinement", "Confinement"),
                    ("Motivation", "Motivation"),
                    ("Humour", "Humour"),
                    ("Actualités", "Actualités"),
                    ("Covid Positif", "Covid Positif"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="texttestimonial",
            name="tags",
            field=models.ManyToManyField(blank=True, to="pages.Tag"),
        ),
    ]
