runtime: custom
env: flex

automatic_scaling:
  min_instances: 1
  max_instances: 5

includes:
  - credentials.yaml

beta_settings:
  cloud_sql_instances: "coco-helvetica-gazette:europe-west6:coco-prod"
